In [2]:
import numpy as np
import time
import timeit

In [2]:
arr = np.array([1, 3, 2, 4, 5])
k = 3
ind = np.argpartition(arr, k)[:k]
ind

array([0, 2, 1], dtype=int64)

In [88]:
arr = np.array([[6, 3, 2, 4, 5],[0, 2, 3, 4, 1]], np.uint8)
k = 3
ind = np.argpartition(arr, k)[:k]
ind

array([[3, 2, 1, 4, 0],
       [0, 4, 1, 2, 3]], dtype=int64)

In [8]:
ind = np.argpartition(arr, k)[:k]
ind

array([[0, 2, 1, 3, 4],
       [0, 4, 1, 2, 3]], dtype=int64)

In [3]:
def smallestN_indices(a, N):
    idx = a.ravel().argsort()[:N]
    return np.stack(np.unravel_index(idx, a.shape)).T

In [17]:
%timeit smallestN_indices(arr, 3)

10.1 µs ± 469 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [7]:
arr = np.array([[6, 3, 2, 4, 5],[0, 2, 3, 4, 1]], np.uint8)
ind = smallestN_indices(arr, 3)
min = arr[tuple(ind.T)]
print(ind.T)
print(min)
ave = np.average(min)
print(ave)

[[1 1 0]
 [0 4 2]]
[0 1 2]
1.0


In [8]:
arr = np.array([[6, 3, 2, 4, 5],[0, 2, 3, 4, 1]], np.uint8)
idx = smallestN_indices(arr[0,:], 1).flatten()
print(idx)
min = arr[1, idx]

print(min)

[2]
[3]


In [84]:
idx = np.argpartition(arr[0,:], 2)[:2]
print(idx)
min = arr[1,:][ind.T]
print(min)

[0 2]
[[0]
 [3]]


In [67]:
tmp = np.array([])
if tmp.size == 0:
    tmp = np.append(tmp,np.array([2, ave]))
tmp = np.vstack((tmp,np.array([2, ave])))
print(tmp)

[[2.         0.66666667]
 [2.         0.66666667]]


In [46]:
for i in range(4, -4, -2):
    print(i)

4
2
0
-2
-4


In [105]:
def smallestN_indices_argparitition(a, N, maintain_order=False):
    idx = np.argpartition(a.ravel(),N)[:N]
    if maintain_order:
        idx = idx[a.ravel()[idx].argsort()]
    return np.stack(np.unravel_index(idx, a.shape)).T

In [109]:
arr = np.array([[6, 3, 2, 4, 5],[0, 2, 3, 4, 1]], np.uint8)
idx = smallestN_indices_argparitition(arr[0,:], 2, maintain_order=False).flatten()
print(idx)
min = arr[1,:][idx]

print(min)

[2 1]
[3 2]
